"""
RQ5: downstream utility of valid vs invalid IDIs for fairness repair.

Are constraint-valid IDIs worth more than invalid ones for repairing a model?
IFT exists to supply discriminatory instances that, added back to training,
reduce the classifier's discrimination. If valid IDIs repair fairness better
per instance than invalid ones, "actionable" stops being a claim and becomes a
measured benefit.

Design (three arms per dataset x classifier x protected attribute):
  none    -- control: original model, no augmentation.
  valid   -- augment training data with N valid IDIs (both members satisfy
             C_tau), generated by CAFT.
  invalid -- augment with N invalid IDIs (raw IDIs that fail two-sided
             validity), from the SAME CAFT run. Using one tool's own raw
             output isolates validity as the only difference between arms;
             tool, generator, and instance distribution are held fixed.

Augmented instances are labelled by majority vote over their protected-attribute
variants (the model-under-test's own predictions), the fair-label convention of
utils/retraining.py; N = retrain_fraction x |train|, matched across arms. Each
arm is repeated with distinct seeds so the valid-vs-invalid comparison carries
Mann-Whitney U and Vargha-Delaney A12.

Metrics after retraining:
  disc_rate   -- individual discrimination rate on a fresh probe sample
                 (fraction of profiles for which flipping the protected
                 attribute changes the prediction). Lower is fairer.
  accuracy    -- accuracy on a held-out test split. Guards against repairing
                 fairness by destroying utility.

Requires CAFT to have been run with --save_all_disc so that both the raw and
valid IDI sets are saved under test_data/CAFT/. Run from the repo root:
    python scripts/run_retraining.py
"""
import argparse
import copy
import os
import sys

import joblib
import numpy as np
import pandas as pd

base_path = os.path.dirname(os.path.abspath(__file__))
root_path = os.path.abspath(os.path.join(base_path, ".."))
os.chdir(root_path)
if root_path not in sys.path:
    sys.path.insert(0, root_path)

from sklearn.base import clone
from sklearn.model_selection import train_test_split

from src.utils.helpers import get_config_dict, get_data, load_disc_inputs

DATASETS    = ['census', 'compas', 'credit', 'bank', 'meps']
DS_MAP      = {'census': 'Census', 'compas': 'COMPAS', 'credit': 'Credit',
               'bank': 'Bank', 'meps': 'MEPS'}
CLASSIFIERS = ['lr', 'rf']          # sklearn refit; DNN handled separately if needed
REPEATS     = 10
RETRAIN_FRACTION = 0.10             # augmentation size as fraction of |train|
PROBE_N     = 20_000                # instances for the post-retrain discrimination probe
OUT_PATH    = 'results/retraining/retraining_runs.csv'


def protected_variants(X, prot_col, lo, hi):
    """All protected-attribute variants of each row: (N, M, d)."""
    vals = np.arange(int(lo), int(hi) + 1)
    M = len(vals)
    N, d = X.shape
    big = np.repeat(X[:, None, :], M, axis=1)
    big[:, :, prot_col] = vals[None, :]
    return big.reshape(N * M, d), M


def disc_rate(model, X_probe, prot_col, lo, hi):
    """Individual discrimination rate: fraction of probe rows whose prediction
    is not constant as the protected attribute sweeps its domain."""
    variants, M = protected_variants(X_probe, prot_col, lo, hi)
    preds = model.predict(variants).reshape(len(X_probe), M)
    varies = preds.max(axis=1) != preds.min(axis=1)
    return float(varies.mean())


def majority_labels(model, X_aug, prot_col, lo, hi):
    """Fair label per augmented row: majority vote of the model's predictions
    over the row's protected-attribute variants (utils/retraining.py convention)."""
    variants, M = protected_variants(X_aug, prot_col, lo, hi)
    preds = model.predict(variants).reshape(len(X_aug), M)
    # Majority vote across variants (binary): round the mean.
    return (preds.mean(axis=1) >= 0.5).astype(int)


def retrain(base_model, X_tr, Y_tr, X_aug, Y_aug):
    """Fresh model of the same class, fit on training data plus augmentation."""
    model = clone(base_model)
    if X_aug is not None and len(X_aug):
        X_fit = np.vstack([X_tr, X_aug])
        Y_fit = np.concatenate([Y_tr, Y_aug])
    else:
        X_fit, Y_fit = X_tr, Y_tr
    model.fit(X_fit, Y_fit)
    return model


def load_pools(config, clf, sname):
    """Return (valid_pool, invalid_pool): CAFT's valid IDIs and the raw IDIs
    that are not valid (same run, isolating validity)."""
    raw = load_disc_inputs('CAFT', config.dataset_name, sname, clf,
                           suffix='disc_inputs')
    try:
        valid = load_disc_inputs('CAFT', config.dataset_name, sname, clf,
                                 suffix='valid_disc_inputs')
    except FileNotFoundError:
        return None, None
    # invalid = raw rows not present in the valid set (row-wise set difference).
    vkeys = {r.tobytes() for r in valid.astype(np.int64)}
    invalid = np.array([r for r in raw.astype(np.int64)
                        if r.tobytes() not in vkeys])
    return valid.astype(np.int64), invalid


def main():
    ap = argparse.ArgumentParser(description='RQ5 retraining utility experiment.')
    ap.add_argument('--repeats', type=int, default=REPEATS)
    ap.add_argument('--retrain_fraction', type=float, default=RETRAIN_FRACTION)
    ap.add_argument('--datasets', default=','.join(DATASETS))
    ap.add_argument('--classifiers', default=','.join(CLASSIFIERS))
    ap.add_argument('--out', default=OUT_PATH,
                    help='output CSV (use a distinct path per augmentation '
                         'fraction; the resume key excludes the fraction)')
    args = ap.parse_args()

    datasets = [d.strip() for d in args.datasets.split(',') if d.strip()]
    classifiers = [c.strip() for c in args.classifiers.split(',') if c.strip()]
    out_path = args.out

    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    cfg = get_config_dict()
    rows, done = [], set()
    if os.path.exists(out_path):
        prev = pd.read_csv(out_path)
        rows = prev.to_dict('records')
        done = {(r['dataset'], r['classifier'], r['attribute'], r['arm'], r['rep'])
                for r in rows}
        print(f'resuming: {len(rows)} runs recorded', flush=True)

    for ds in datasets:
        config = cfg[ds]
        X, Y, _, _ = get_data(config.dataset_name)()
        X = np.asarray(X); Y = np.asarray(Y).ravel()
        for clf in classifiers:
            mpath = os.path.join('models', ds, f'{clf}.pkl')
            if not os.path.exists(mpath):
                continue
            base_model = joblib.load(mpath)
            for sp, sname in config.sens_name.items():
                prot_col = sp - 1
                lo, hi = config.input_bounds[prot_col]
                valid_pool, invalid_pool = load_pools(config, clf, sname)
                if valid_pool is None or len(valid_pool) == 0 or len(invalid_pool) == 0:
                    print(f'  {ds}/{clf}/{sname}: missing valid/invalid pool, skip',
                          flush=True)
                    continue

                for rep in range(args.repeats):
                    rng = np.random.default_rng(2000 + rep)
                    X_tr, X_te, Y_tr, Y_te = train_test_split(
                        X, Y, test_size=0.2, random_state=rep)
                    n_aug = min(int(args.retrain_fraction * len(X_tr)),
                                len(valid_pool), len(invalid_pool))
                    probe = X_te if len(X_te) <= PROBE_N else \
                        X_te[rng.choice(len(X_te), PROBE_N, replace=False)]

                    for arm, pool in [('none', None), ('valid', valid_pool),
                                      ('invalid', invalid_pool)]:
                        if (ds, clf, sname, arm, rep) in done:
                            continue
                        if pool is None:
                            X_aug = Y_aug = None
                        else:
                            idx = rng.choice(len(pool), n_aug, replace=False)
                            X_aug = pool[idx]
                            Y_aug = majority_labels(base_model, X_aug, prot_col, lo, hi)
                        model = retrain(base_model, X_tr, Y_tr, X_aug, Y_aug)
                        dr = disc_rate(model, probe, prot_col, lo, hi)
                        acc = float((model.predict(X_te) == Y_te).mean())
                        rec = {
                            'dataset': DS_MAP[ds], 'classifier': clf,
                            'attribute': sname, 'arm': arm, 'rep': rep,
                            'n_aug': 0 if X_aug is None else n_aug,
                            'disc_rate': round(dr, 5), 'accuracy': round(acc, 5),
                        }
                        rows.append(rec)
                        pd.DataFrame(rows).to_csv(out_path, index=False)
                    print(f'  {ds}/{clf}/{sname} rep{rep}: n_aug={n_aug} done',
                          flush=True)

    long = pd.DataFrame(rows)
    if long.empty:
        print('no runs produced')
        return
    print('\n=== mean by arm (disc_rate lower=fairer, accuracy higher=better) ===')
    print(long.groupby('arm').agg(disc_rate=('disc_rate', 'mean'),
                                  accuracy=('accuracy', 'mean')).round(4).to_string())
    print('\nRETRAINING_OK', flush=True)


if __name__ == '__main__':
    main()
